name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Get the version
        run: echo ::set-env name=APP_VERSION::${GITHUB_REF#refs/tags/v}

      - name: Copy .env environment
        run: cp .env.example .env

      - name: Build and publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          PORT: 3333
          APP_KEY: ${{secrets.APP_KEY}}
          APP_DETECT_PROVIDER: ${{secrets.APP_DETECT_PROVIDER}}
        with:
          name: 12bayvn/airport-detection
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'latest,${{ env.APP_VERSION }}'
          buildargs: APP_VERSION,PORT,APP_KEY,APP_DETECT_PROVIDER
